# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.26.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1404921030640
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.2
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.5
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [393]:
x = np.array([1,2,3,4])
print(x.size)
print(x.itemsize)
print(x.size * x.itemsize)

4
4
16
4
4
16


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [394]:
# python -c "import numpy as np; help(np.add)"
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [395]:
null = np.zeros(10)
null[4] = 1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [396]:
ten_to_fortyNine = np.arange(start=10,stop = 50)
ten_to_fortyNine

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [397]:
three_three_matrix = np.arange(start=0,stop=9).reshape(3,3)
three_three_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [398]:
x = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(x)
non_zero

(array([0, 1, 4], dtype=int64),)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [399]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [400]:
np.random.rand(3,3,3)

array([[[0.28275818, 0.23551677, 0.95093039],
        [0.89159571, 0.68213206, 0.81551507],
        [0.3623496 , 0.40185084, 0.98170346]],

       [[0.61086685, 0.28477678, 0.86664597],
        [0.12856507, 0.7539128 , 0.92644303],
        [0.94591587, 0.81545723, 0.31587044]],

       [[0.31364862, 0.53252144, 0.39018872],
        [0.50398255, 0.90440067, 0.36239471],
        [0.58662896, 0.96994254, 0.28663181]]])

array([[[0.59529806, 0.73127134, 0.09614741],
        [0.43791078, 0.99294113, 0.77090315],
        [0.57638662, 0.75266512, 0.81581831]],

       [[0.81849135, 0.11256854, 0.17897196],
        [0.09255734, 0.50151706, 0.57957287],
        [0.06309034, 0.2314376 , 0.71152371]],

       [[0.80128157, 0.18024683, 0.26564672],
        [0.9310531 , 0.67396523, 0.63158724],
        [0.92099117, 0.35568789, 0.25266604]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [401]:
ten_ten = np.random.rand(10,10)
print(f"maximum_val = {np.max(ten_ten)}")
print(f"minimum_val = {np.min(ten_ten)}")

maximum_val = 0.9989676300703874
minimum_val = 0.004691841262238983
maximum_val = 0.9996033323068076
minimum_val = 0.03246907599577031


In [402]:
import numpy as np

arr = np.array([1, 5, 3, 7, 2])
max_value = np.max(arr)

print("Maximum value in the array:", max_value)


Maximum value in the array: 7
Maximum value in the array: 7


In [403]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 6, 5], [7, 8, 9]])
max_value = np.max(matrix)

print("Maximum value in the matrix:", max_value)


Maximum value in the matrix: 9
Maximum value in the matrix: 9


In [404]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

max_values_along_columns = np.max(matrix, axis=0)
max_values_along_rows = np.max(matrix, axis=1)

print("Maximum values along columns:", max_values_along_columns)
print("Maximum values along rows:", max_values_along_rows)


Maximum values along columns: [7 8 9]
Maximum values along rows: [3 6 9]
Maximum values along columns: [7 8 9]
Maximum values along rows: [3 6 9]


In [405]:
import numpy as np

matrix_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

max_values_along_first_axis = np.max(matrix_3d, axis=0)

max_values_along_rows = np.max(matrix_3d, axis=1)

max_values_along_columns = np.max(matrix_3d, axis=2)

print("Maximum values along the first axis (axis 0):")
print(max_values_along_first_axis)

print("\nMaximum values along columns (axis 1):")
print(max_values_along_rows)

print("\nMaximum values along rows (axis 2):")
print(max_values_along_columns)


Maximum values along the first axis (axis 0):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Maximum values along columns (axis 1):
[[7 8 9]]

Maximum values along rows (axis 2):
[[3 6 9]]
Maximum values along the first axis (axis 0):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Maximum values along columns (axis 1):
[[7 8 9]]

Maximum values along rows (axis 2):
[[3 6 9]]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [406]:
vector_30 = np.random.rand(30)
mean_vector_30 = np.mean(vector_30)
mean_vector_30

0.4902520024922614

0.5264808646271377

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [407]:
import numpy as np

matrix = np.ones((5,5))
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [408]:
ones = np.ones((5,5))
print(matrix.shape)
new_shape = np.array(matrix.shape)
print(new_shape)
new_shape = tuple(new_shape+2)
print(new_shape)

zeros = np.zeros(new_shape)
zeros[1:-1, 1:-1] = ones

print(zeros)

(5, 5)
[5 5]
(7, 7)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
(5, 5)
[5 5]
(7, 7)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [409]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.inf<np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))

nan
False
False
False
nan
True
nan
False
False
False
nan
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [410]:
import numpy as np

matrix = np.diag(np.arange(1, 5), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [411]:
import numpy as np

# Create an 8x8 matrix with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)



checkerboard_matrix[::2,1::2] = 1
checkerboard_matrix[1::2, ::2] = 1

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [412]:
x = np.random.rand(6,7,8)
y = x.flatten()
print(y.shape)
val_at_100 = y[99]
print(val_at_100)
index_of_val = np.argwhere(x  == val_at_100)
index_of_val

(336,)
0.17243797402355532


array([[1, 5, 3]], dtype=int64)

(336,)
0.017392244319899164


array([[1, 5, 3]], dtype=int64)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [413]:
x  =np.array([[1,0],[0,1]])
x = np.tile(x, (4,4))
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [414]:
x = np.random.rand(5,5)

max_val = np.max(x)
min_val = np.min(x)

print((x-min_val)/(max_val-min_val))

[[0.51397611 0.         0.74118329 0.24748713 0.5376987 ]
 [0.17983061 0.73010594 0.60037626 0.97471966 0.92459566]
 [0.75889894 0.55707472 0.01091194 1.         0.51532599]
 [0.10195163 0.10086338 0.6164782  0.09049743 0.09617996]
 [0.3607372  0.37945714 0.85377227 0.55571605 0.77559148]]
[[0.52680712 0.9859809  0.83383905 0.         0.14426742]
 [0.82714085 0.50489148 0.14078234 0.65260772 0.95105283]
 [1.         0.92688546 0.09367482 0.83398672 0.38941594]
 [0.13952851 0.85224226 0.36918142 0.01421122 0.87269781]
 [0.72897532 0.40096507 0.21612133 0.08219347 0.79058219]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [415]:
rgba_dtype = np.dtype([('R',np.uint8), ('G',np.uint8) ,('B',np.uint8), ('A',np.uint8)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [416]:
x = np.random.rand(5,3)
y = np.random.rand(3,2)

np.matmul(x,y), np.dot(x,y)

(array([[0.79075754, 0.3949275 ],
        [0.53870269, 0.23078843],
        [0.73025035, 0.28060391],
        [0.87266817, 0.35633657],
        [0.68288718, 0.24990054]]),
 array([[0.79075754, 0.3949275 ],
        [0.53870269, 0.23078843],
        [0.73025035, 0.28060391],
        [0.87266817, 0.35633657],
        [0.68288718, 0.24990054]]))

(array([[0.7502092 , 0.62893502],
        [1.03864152, 0.95629131],
        [0.45303139, 0.58143494],
        [0.73240332, 0.61895292],
        [0.24157251, 0.29151129]]),
 array([[0.7502092 , 0.62893502],
        [1.03864152, 0.95629131],
        [0.45303139, 0.58143494],
        [0.73240332, 0.61895292],
        [0.24157251, 0.29151129]]))

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [417]:
x = np.arange(1,10)
for i,val in enumerate(x):
    if 3 < val < 8:
        x[i] = val*-1

print(x)

[ 1  2  3 -4 -5 -6 -7  8  9]
[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [418]:
print(range(5))
print(range(5) ,-1)
print(sum(range(5),-1))

range(0, 5)
range(0, 5) -1
9
range(0, 5)
range(0, 5) -1
9


In [419]:
print(np.add(range(5),-1))

[-1  0  1  2  3]
[-1  0  1  2  3]


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [420]:
# all except Last one is legal

In [421]:
Z = 2
print(Z**Z)
print(4<<Z)
print(4 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

4
16
4
False
2j
2.0
False
4
16
4
False
2j
2.0
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [422]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Muhammad Hamza\AppData\Local\Temp\ipykernel_13808\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Muhammad Hamza\AppData\Local\Temp\ipykernel_13808\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Muhammad Hamza\AppData\Local\Temp\ipykernel_13808\1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\Muhammad Hamza\AppData\Local\Temp\ipykernel_13808\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Muhammad Hamza\AppData\Local\Temp\ipykernel_13808\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Muhammad Hamza\AppData\Local\Temp\ipykernel_13808\1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [423]:
x = np.array([-3.14, 2.718, -1.5, 3.33, -0.7])
final = np.where(x >= 0, np.ceil(x), np.floor(x))

print(x)
print(final)


[-3.14   2.718 -1.5    3.33  -0.7  ]
[-4.  3. -2.  4. -1.]
[-3.14   2.718 -1.5    3.33  -0.7  ]
[-4.  3. -2.  4. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [424]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[3, 4, 5], [6, 7, 8]])
val,index1,index2 = np.intersect1d(x,y,return_indices=True)
val,index1,index2

(array([3, 4, 5, 6]),
 array([2, 3, 4, 5], dtype=int64),
 array([0, 1, 2, 3], dtype=int64))

(array([3, 4, 5, 6]),
 array([2, 3, 4, 5], dtype=int64),
 array([0, 1, 2, 3], dtype=int64))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [439]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-12-19
Today: 2023-12-20
Tomorrow: 2023-12-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [426]:
import numpy as np


print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))


March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']
March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [427]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

result = ((A+B)*(-A/2))
result

array([ -2.5,  -7. , -13.5])

array([ -2.5,  -7. , -13.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [428]:
x = np.random.uniform(1, 5, size=10)
print(x)
print(np.floor(x))
print(np.ceil(x))
print(np.round(x))
print(np.trunc(x))
print(x.astype(int))

[1.6719796  1.44858365 3.59275013 4.62122479 4.94864128 1.09289908
 4.75232164 1.03832744 1.7414528  2.19156994]
[1. 1. 3. 4. 4. 1. 4. 1. 1. 2.]
[2. 2. 4. 5. 5. 2. 5. 2. 2. 3.]
[2. 1. 4. 5. 5. 1. 5. 1. 2. 2.]
[1. 1. 3. 4. 4. 1. 4. 1. 1. 2.]
[1 1 3 4 4 1 4 1 1 2]
[2.10278065 4.56631098 4.34422361 3.69774441 1.50193019 4.88333488
 4.52325279 2.3769036  2.42573078 2.57426343]
[2. 4. 4. 3. 1. 4. 4. 2. 2. 2.]
[3. 5. 5. 4. 2. 5. 5. 3. 3. 3.]
[2. 5. 4. 4. 2. 5. 5. 2. 2. 3.]
[2. 4. 4. 3. 1. 4. 4. 2. 2. 2.]
[2 4 4 3 1 4 4 2 2 2]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [429]:
np.random.randint(0,5,25).reshape(5,5)

array([[4, 2, 4, 3, 2],
       [3, 4, 4, 3, 2],
       [1, 3, 1, 1, 4],
       [3, 3, 0, 0, 0],
       [0, 4, 3, 3, 1]])

array([[2, 4, 1, 2, 4],
       [0, 1, 2, 1, 0],
       [2, 1, 1, 3, 0],
       [3, 0, 1, 1, 1],
       [1, 3, 3, 1, 2]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [430]:
import numpy as np

def generate_integers():
    for i in range(10):
        yield i

result = np.fromiter(generate_integers(), dtype=int)

print("Generated Array:", result)


Generated Array: [0 1 2 3 4 5 6 7 8 9]
Generated Array: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [431]:
np.linspace(0, 1, 20)[1:-1],np.arange(0,1,0.1)[1:-1]


(array([0.05263158, 0.10526316, 0.15789474, 0.21052632, 0.26315789,
        0.31578947, 0.36842105, 0.42105263, 0.47368421, 0.52631579,
        0.57894737, 0.63157895, 0.68421053, 0.73684211, 0.78947368,
        0.84210526, 0.89473684, 0.94736842]),
 array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]))

(array([0.05263158, 0.10526316, 0.15789474, 0.21052632, 0.26315789,
        0.31578947, 0.36842105, 0.42105263, 0.47368421, 0.52631579,
        0.57894737, 0.63157895, 0.68421053, 0.73684211, 0.78947368,
        0.84210526, 0.89473684, 0.94736842]),
 array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]))

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [432]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, 3, 3, 4, 4,])

x[y] += 1

x

array([0, 2, 2, 4, 5])

array([0, 2, 2, 4, 5])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [433]:
# Given data
X = [1, 2, 3, 4, 5]
F = [0, 0, 0, 0, 0]
I = [1, 3, 2, 0]

# Accumulate elements from X into F based on indices in I
for i, index in enumerate(I):
    F[i] += X[index]

# Result
print(F)


[2, 4, 3, 1, 0]
[2, 4, 3, 1, 0]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [435]:

w, h = 10,10
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)
pixels = image.reshape((-1, 3))
pixels_list = [tuple(pixel) for pixel in pixels]
unique_colors = set(pixels_list)

print(len(unique_colors))



100
100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [441]:
x = np.random.rand(2, 2, 2, 2)

y = np.sum(x, axis=(-2,-1))

print(x)
print(y)


[[[[0.04226631 0.70458769]
   [0.33566954 0.61637745]]

  [[0.60619635 0.61247525]
   [0.31095871 0.9144641 ]]]


 [[[0.27375209 0.43060828]
   [0.50420944 0.35986575]]

  [[0.17467556 0.94595432]
   [0.35496462 0.29974052]]]]
[[1.69890099 2.44409441]
 [1.56843557 1.77533502]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [437]:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 1, 1, 2, 2, 3, 3, 3, 3])

unique_subset = np.unique(S)

means = []
for subset in unique_subset:
    indices = np.where(S == subset)
    means.append(np.mean(D[indices]))

print(D)
print(S)
print(means)


[ 1  2  3  4  5  6  7  8  9 10]
[0 0 1 1 2 2 3 3 3 3]
[1.5, 3.5, 5.5, 8.5]
[ 1  2  3  4  5  6  7  8  9 10]
[0 0 1 1 2 2 3 3 3 3]
[1.5, 3.5, 5.5, 8.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [448]:
# Example matrices
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

result = np.dot(A, B)
print(np.diagonal(result))

[0.69019209 0.49060636 0.81319074]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [455]:
x = np.array([1, 2, 3, 4, 5])
new_shape = len(x)*3
print(new_shape)

zeros = np.zeros()

ValueError: can only convert an array of size 1 to a Python scalar

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)