### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [171]:
import numpy as np

x = np.random.rand(5,5)
print(x)
x[0, :], x[-1,:] = x[-1,:].copy() , x[0,:].copy()
print(x)


[[0.23224417 0.05758769 0.51126002 0.79757687 0.89690166]
 [0.165166   0.35545091 0.24385826 0.87435382 0.38491389]
 [0.05777661 0.09794668 0.59114571 0.13203726 0.92743898]
 [0.66825182 0.98167455 0.96137556 0.02334118 0.60759922]
 [0.12937039 0.45464708 0.98288557 0.66744016 0.01777538]]
[[0.12937039 0.45464708 0.98288557 0.66744016 0.01777538]
 [0.165166   0.35545091 0.24385826 0.87435382 0.38491389]
 [0.05777661 0.09794668 0.59114571 0.13203726 0.92743898]
 [0.66825182 0.98167455 0.96137556 0.02334118 0.60759922]
 [0.23224417 0.05758769 0.51126002 0.79757687 0.89690166]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [172]:
x = np.arange(0,9).reshape(3,3)

x_without_zeros = []
for row in x:
    if all(num != 0 for num in row):
        x_without_zeros.append(row)

x_without_zeros = np.array(x_without_zeros)
print(x_without_zeros)


[[3 4 5]
 [6 7 8]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [173]:
import numpy as np

x = np.array([1.00000000 +0.j, 0.70710678 + 0.70710678j])

real_parts = []
imag_parts = []

for num in x:
    num_str = str(num)
    parts = num_str.split('+')
    real_part = parts[0][1:]
    imag_part = parts[1][0:-2]
    real_parts.append(real_part)
    imag_parts.append(imag_part)

print(real_parts)
print(imag_parts)


['1', '0.70710678']
['0', '0.70710678']



### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [174]:
x = [10, 10, 20, 20, 30, 30]

mylist = []
for num in x:
    if num not in mylist:
        mylist.append(num)

print(mylist)


[10, 20, 30]


### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [175]:
np.random.rand(3,3,3)

array([[[0.63352467, 0.69025899, 0.84182498],
        [0.60979215, 0.76709289, 0.96071236],
        [0.21838691, 0.50186649, 0.76089223]],

       [[0.70920968, 0.24520148, 0.20662493],
        [0.11992187, 0.04419861, 0.53634995],
        [0.96685901, 0.81910332, 0.97034183]],

       [[0.02903504, 0.24798672, 0.3594154 ],
        [0.02807154, 0.14786531, 0.48276718],
        [0.0761319 , 0.30916317, 0.97413748]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [176]:
x = np.random.randint(1,10,10)
print(x)

n = len(x)
for i in range(n-1):
    for j in range(n-i-1):
        if x[j] > x[j+1]:
            x[j], x[j + 1] = x[j + 1], x[j]

print(x)

[6 4 9 3 2 9 3 4 2 1]
[1 2 2 3 3 4 4 6 9 9]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [177]:
x = np.random.rand(2,2)
y = np.random.rand(2,2)
print(x)
print(y)
Flag = True
for i in range(len(x)):
    for j in range(i):
        if x[i][j] != y[i][j]:
            Flag = False

if Flag:
    print("Both are equal")
else:
    print("Not Equal")



[[0.86260487 0.96417287]
 [0.88686227 0.64343803]]
[[0.14035465 0.79189949]
 [0.12872284 0.675676  ]]
Not Equal


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [178]:
x = np.array([[10, 40],
              [30, 20]])

print(np.sort(x, axis=0))
print(np.sort(x, axis=1))
print(np.sort(x.flatten()))

#################### sorting ##################
x = x.flatten()

n = len(x)
for i in range(n-1):
    for j in range(n-i-1):
        if x[j] > x[j+1]:
            x[j], x[j + 1] = x[j + 1], x[j]

print(x)

print(x.reshape(2,2))

[[10 20]
 [30 40]]
[[10 40]
 [20 30]]
[10 20 30 40]
[10 20 30 40]
[[10 20]
 [30 40]]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [179]:
arr = [-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2. ]

ceils = []
for x in arr:
    if isinstance(x, int):
        ceils.append(x)

    if x >= 0:
        ceils.append(int(x) + 1)

    else:
        ceils.append(int(x))

print(ceils)

[-1, -1, 0, 1, 2, 2, 3]


In [180]:
floors = []
for x in arr:
    if isinstance(x, int):
        floors.append(x)
    if x >= 0:
        floors.append(int(x))
    else:
        floors.append(int(x) - 1)

print(floors)

[-2, -2, -1, 0, 1, 1, 2]


In [181]:
truncats = []
for x in arr:
    truncats.append(int(x))

print(truncats)

[-1, -1, 0, 0, 1, 1, 2]


In [182]:
arr = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2. ])

print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))


2.0
2.0
2.0


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [183]:
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [184]:
from datetime import datetime, timedelta

base_date = datetime(2000, 1, 1, 0, 0, 0)
print(base_date)
date_objects = [base_date + timedelta(hours=i) for i in range(24)]
numpy_array = np.array(date_objects)
print(numpy_array)


2000-01-01 00:00:00
[datetime.datetime(2000, 1, 1, 0, 0) datetime.datetime(2000, 1, 1, 1, 0)
 datetime.datetime(2000, 1, 1, 2, 0) datetime.datetime(2000, 1, 1, 3, 0)
 datetime.datetime(2000, 1, 1, 4, 0) datetime.datetime(2000, 1, 1, 5, 0)
 datetime.datetime(2000, 1, 1, 6, 0) datetime.datetime(2000, 1, 1, 7, 0)
 datetime.datetime(2000, 1, 1, 8, 0) datetime.datetime(2000, 1, 1, 9, 0)
 datetime.datetime(2000, 1, 1, 10, 0) datetime.datetime(2000, 1, 1, 11, 0)
 datetime.datetime(2000, 1, 1, 12, 0) datetime.datetime(2000, 1, 1, 13, 0)
 datetime.datetime(2000, 1, 1, 14, 0) datetime.datetime(2000, 1, 1, 15, 0)
 datetime.datetime(2000, 1, 1, 16, 0) datetime.datetime(2000, 1, 1, 17, 0)
 datetime.datetime(2000, 1, 1, 18, 0) datetime.datetime(2000, 1, 1, 19, 0)
 datetime.datetime(2000, 1, 1, 20, 0) datetime.datetime(2000, 1, 1, 21, 0)
 datetime.datetime(2000, 1, 1, 22, 0) datetime.datetime(2000, 1, 1, 23, 0)]


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [185]:
x = np.array(['Python', 'PHP'])
y = np.array([' Java', ' C++'])
array = np.empty(len(x)*len(y), dtype='object')

for i in range(2):
    array[i] = x[i]
    array[i+1] = y[i]

print(array)


['Python' 'PHP' ' C++' None]
